sudo: required
services:
 - docker

before_install:
 - docker build -t coolshaddy/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run coolshaddy/react-test npm test -- --coverage --watchAll=false

after_success:
 - docker build -t coolshaddy/multi-client:latest ./client 
 - docker build -t coolshaddy/multi-nginx:latest ./nginx
 - docker build -t coolshaddy/multi-server:latest ./server
 - docker build -t coolshaddy/multi-worker:latest ./worker
 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
 - docker push coolshaddy/multi-client:latest
 - docker push coolshaddy/multi-nginx:latest
 - docker push coolshaddy/multi-server:latest
 - docker push coolshaddy/multi-worker:latest